### ISSUE TITLE
Theme Switcher should close when someone clicks outside of the component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#12] opened 2022-09-14 15:04 UTC
**Describe the bug**
When the theme switcher dropdown is open and someone clicks outside of the component with a mouse, the dropdown should close and focus should return to the button.

**Comment by ctoffanin** [comment] 2022-09-24 11:36
Hi Emma, can I be assigned to this?
I decided to join hacktoberfest. I'll wait till it starts.

**Comment by EmmaDawsonDev** [comment] 2022-09-24 11:38
Sure!

**Comment by ctoffanin** [comment] 2022-10-02 09:25
Hi, @EmmaDawsonDev! I'm getting some issues with this one (my skills in React are not so awesome).
I was trying to handle the click from within the Theme Switcher component. The problem is that it "conflicts" with the button onClick (I have difficulties differentiating between the 2).
I was thinking of adding a hook or a new component acting as a listener and wrapping the `ul` tag with it to handle the click outside.
I see npm packages are doing this thing (i.e. [this](https://www.npmjs.com/package/react-click-away-listener)).
Let me know what your idea/approach on this one is.

**Comment by EmmaDawsonDev** [comment] 2022-10-02 09:43
No worries, I was also having similar issues which is why I created an issue to do it later :D I think this is probably what we need: https://usehooks-ts.com/react-hook/use-on-click-outside this is what we use at work to achieve the same thing.

**Comment by EmmaDawsonDev** [comment] 2022-10-02 09:45
You can make a new folder called customHooks and pop it in there.

**Comment by ctoffanin** [comment] 2022-10-02 09:50
Perfect, so my idea of a hook was on the right path.

**Comment by ctoffanin** [comment] 2022-10-02 12:52
This is nice! I have so many stashes saved 😂 
Also, instant bookmark of [usehooks-ts.com](https://usehooks-ts.com/)!

**Closed** 2022-10-02 19:01 UTC
Labels: hacktoberfest
