### ISSUE TITLE
Import WIP component into AudioTemplate

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#94] opened 2022-10-06 19:29 UTC
Please import the WorkInProgress component into the AudioTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by jyotika6221** [comment] 2022-10-08 14:55
hey, if the issue is still open, i can fix it. please assign it to me.

**Comment by EmmaDawsonDev** [comment] 2022-10-08 14:56
Sure, go ahead @jyotika6221

**Comment by jyotika6221** [comment] 2022-10-08 14:58
ok.

**Comment by jyotika6221** [comment] 2022-10-09 19:08
Can you please elaborate how to work on this issue? I'm facing difficulty.

**Comment by EmmaDawsonDev** [comment] 2022-10-09 19:56
Sure. How far have you gotten?

**Comment by jyotika6221** [comment] 2022-10-09 20:41
I forked and cloned the repository , went through the AlertTemplates component to see how is it done and saw the code.
But kindly tell me which file do i need to add this code to? Or if something else needs to be done please explain. 
Thank you.

**Comment by EmmaDawsonDev** [comment] 2022-10-09 21:06
If you look in the folder Components/ContentTemplates you will find a file called AudioTemplate.

It currently looks like this 
```
import React from "react"

const AudioTemplate = () => {
	return <div>AudioTemplate</div>
}

export default AudioTemplate
```

Update it so it looks like this instead: 
```
import React from "react"
import WorkInProgress from "../WorkInProgress/WorkInProgress"

const AudioTemplate = () => {
	return <WorkInProgress />
}

export default AudioTemplate
```

**Comment by jyotika6221** [comment] 2022-10-09 21:31
Thank you, i have requested for the pr.

**Closed** 2022-10-10 05:00 UTC
Labels: good first issue, hacktoberfest, JSX
